version: '3'

services:
  postgres:
    image: postgres:17
    container_name: postgres_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: '4gb'
    networks:
      - DE-network
