version: "3"
services:
  fe:
    image: apache/doris:fe-3.0.7
    hostname: fe
    container_name: doris-fe
    environment:
      - FE_SERVERS=fe1:172.20.0.188:9010
      - FE_ID=1
      - JAVA_OPTS_FOR_JDK_17=-Xms6g -Xmx6g -XX:+UseG1GC
    volumes:
      - ./data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
      - ./data/fe/conf:/opt/apache-doris/fe/conf
      - ./data/fe/log/:/opt/apache-doris/fe/log/
    network_mode: host
    restart: always

  be:
    image: apache/doris:be-3.0.7
    hostname: be
    container_name: doris-be
    environment:
      - FE_SERVERS=fe1:172.20.0.188:9010
      - BE_ADDR=172.20.0.188:9050
    volumes:
      - ./data/be/storage/:/opt/apache-doris/be/storage/
      - ./data/be/conf:/opt/apache-doris/be/conf  
      - ./data/be/script/:/docker-entrypoint-initdb.d/
      - ./data/be/log:/opt/apache-doris/be/log

    depends_on:
      - fe
    network_mode: host
    restart: always
