cluster.name: "elk-cluster"
node.name: "es-hot"

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Node roles - master + hot data + ingest
node.roles: [ master, data_hot, data, ingest, data_content, remote_cluster_client ]

# Node attributes for data tiers
node.attr.data: hot


# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory settings
bootstrap.memory_lock: true

# Security settings (enabled to match Docker Compose)
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true

# Index settings for hot tier
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

s3.client.default.endpoint: s3.ap-south-1.amazonaws.com
s3.client.default.region: ap-south-1
