version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart : unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mysql-network
volumes:
  mysql-data:
networks:
  mysql-network:
    external: true
