version: '3.8'

services:
  minio1:
    image: quay.io/minio/minio
    container_name: minio1
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    volumes:
      - ${HOME}/minio/data:/data
    command: server /data --console-address ":9001"
    user: "${UID}:${GID}"
    networks:
      - DE-network

networks:
  DE-network:
    external: true
