kafka:
  clusters:
  - bootstrapServers: ip:9092
    kafkaConnect:
    - address: http://ip:8083
      name: SQL Connector
    - address: http://ip:8084
      name: Common Connectors
    ksqldbServer: http://ip:8088
    name: Kafka
    properties: {}
    readOnly: false
    schemaRegistry: http://ip:8081
auth:
  type: OAUTH2
  oauth2:
    client:
      google:
        provider: google
        clientId: Google Client ID
        clientSecret: Google Secret ID
        redirect-uri: https://url/login/oauth2/code/google
        user-name-attribute: email
        custom-params:
          type: google
          allowedDomain: 
webclient: {}
